name: CI

on:
  push:
    branches:
      - ci-test
  pull_request:
    branches:
      - ci-test

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  # Build the docs using `pnpm run build`, and then upload `dist/` as a build artifact,
  # allowing any dependent jobs to use the output without having to re-run the build.
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build Docs
        run: pnpm run build

      - name: Upload Build Output
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
          if-no-files-found: error

  # Run `pnpm run lint:linkcheck:nobuild` on the build output generated by the `build` job
  linkcheck:
    name: Check for Broken Links
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Download Build Output
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Check for Broken Links
        run: pnpm run lint:linkcheck:nobuild
